chore: create and export FPD without bbn chain
babylonchain/finality-provider pull request #286
Opened 2024-04-16 19:00 UTC by RafilxTenfen

- Add new cli command `fpcli p1-export-finality-provider` that stores a new finality provider in the database and record the keys on the eots manager connected to it without bbn chain running (it does not send tx to bbn to register the fpd)
- Instead of registering the finality provider onchain it prints out the stored finality provider

2024-04-17 14:08 UTC, vitsalis requested changes

2024-04-17 14:08 UTC, vitsalis commented on docs/phase-1/finality-provider.md
> +# Finality Provider
Let's wrap `.md` files to 80 char lines.

2024-04-17 14:08 UTC, vitsalis commented on docs/phase-1/finality-provider.md
> +Finality providers are responsible for voting at a finality round on top of CometBFT. Similar to any native PoS validator, a finality provider can receive voting power delegations from BTC stakers, a
```suggestion
Finality providers are responsible for voting at a finality round on top of CometBFT that is powered by BTC stake.
Similar to any native PoS validator, a finality provider can receive voting power delegations from BTC stakers, and through their voting power provide economic security to the underlying PoS protocol.

In this document,
we explore how someone can create a finality provider and export details about it in JSON format.
```

2024-04-17 14:08 UTC, vitsalis commented on docs/phase-1/finality-provider.md
> +# Finality Provider
Also, don't think this should be underneath a `phase-1` folder. The new functionality is about exporting finality provider information, doesn't have anything to do with the phase. Would also recommend renaming the file to `finality-provider-export.md`

2024-04-17 14:08 UTC, vitsalis commented on docs/phase-1/finality-provider.md
> +- Start by creating the finality provider config, this config is needed to define the `[dbconfig]` where it is set the path and database configurations
Do we need to use bullets here? Why not just a sequence of sentences?

2024-04-17 14:08 UTC, vitsalis commented on docs/phase-1/finality-provider.md
> +$~ fpd init --home ./phase-1/fpd
```suggestion
$ fpd init --home ./phase-1/fpd
```

Same for others.

We should also show sample outputs of commands and explain what the CLI flags are.

2024-04-17 14:08 UTC, vitsalis commented on docs/phase-1/finality-provider.md
> +- The finality provider need a private and public key on the consumer chain, in this case `babylon`, for creating a key run the following.:
```suggestion
The finality provider requires a key pair on the PoS chain it aims to secure. The chain is identified by its chain ID.
```

Also explanation on the other CLI flags.

2024-04-17 14:08 UTC, vitsalis commented on docs/phase-1/finality-provider.md
> +- Each finality provider needs to provide public randomness, for generating and managing such a thing the eots is used. Start by initiating the config file of eots with:
> for generating and managing such a thing the eots is used. 

Don't get what this means.

Below we explain how we set up the EOTS manager. We can write a sentence about what it is and why it is needed and explain that operations on it happen through the `eotsd` executable.

2024-04-17 14:08 UTC, vitsalis commented on docs/phase-1/finality-provider.md
> +- In another terminal, start the eots manager daemon.
Why do we need the eots manager daemon to be operational? Ideally we should be able to do this in just CLI mode without the need to run daemons.

2024-04-17 14:08 UTC, vitsalis commented on docs/phase-1/finality-provider.md
> +- On this phase no babylon or consumer chain is not running, so it is not possible to register the finality provider onchain, but for BTC delegations to choose your finality provider
I don't think we need to provide this information. This document is on creating the finality provider information and exporting it.

2024-04-17 14:08 UTC, vitsalis commented on docs/phase-1/finality-provider.md
> +$~ fpcli p1-export-finality-provider --home ./phase-1/fpd --key-name finality-provider --chain-id babylon-1 --commission 0.05 --moniker my-fp-nickname --identity anyIdentity --website www.my-public-a
This is a very long command, let's split it in multiple lines.

2024-04-17 16:37 UTC, RafilxTenfen commented on docs/phase-1/finality-provider.md
> +# Finality Provider
done at https://github.com/babylonchain/finality-provider/pull/286/commits/7f9dadbaaf625ad9e3473a7195b2e1c96399444a

2024-04-17 16:37 UTC, RafilxTenfen commented on docs/phase-1/finality-provider.md
> +Finality providers are responsible for voting at a finality round on top of CometBFT. Similar to any native PoS validator, a finality provider can receive voting power delegations from BTC stakers, a
https://github.com/babylonchain/finality-provider/pull/286/commits/7f9dadbaaf625ad9e3473a7195b2e1c96399444a

2024-04-17 18:12 UTC, RafilxTenfen commented on docs/phase-1/finality-provider.md
> +- In another terminal, start the eots manager daemon.
We could connect to the eots database directly from the fpcli, but that could be a bit messy and couple a lot the code packages

2024-04-18 02:50 UTC, SebastianElvis commented on docs/finality-provider-export.md
> +$ fpcli export-finality-provider --home ./export-fp/fpd --key-name finality-provider \
Tbh I feel the above sections are not relevant to this doc, whose focus is exporting a finality provider to JSON format.

So probably

- The above sections could be merged to `docs/finality-provider.md`
- The doc related to exporting command could be merged to `README.md`

Wdyt?

2024-04-18 02:50 UTC, SebastianElvis commented on finality-provider/cmd/fpcli/daemon/export-fpd.go
> +		cli.StringFlag{
I'm not sure if this field and the below ones are needed for exporting a fp. They can be fetced from DB rather than being provided by the user.

2024-04-18 02:50 UTC, SebastianElvis commented on finality-provider/cmd/fpcli/daemon/export-fpd.go
> +		SlashedBtcHeight:     0,
These fields are stateful and out of control for the finality provider operator. So probably we are not using the right protobuf object. However, I'm not sure if we have one without these fields :sweat:

2024-04-18 10:33 UTC, RafilxTenfen commented on docs/finality-provider-export.md
> +$ fpcli export-finality-provider --home ./export-fp/fpd --key-name finality-provider \
I think the idea for this `docs/finality-provider-export.md` file is to have instructions for finality providers on how they can create and export their data to register themselves without a bbn chain active

One thought is to receive this registration by pull requests in a github repository, but I believe it would be another repository

2024-04-18 10:37 UTC, RafilxTenfen commented on finality-provider/cmd/fpcli/daemon/export-fpd.go
> +		cli.StringFlag{
This CLI creates and export an fpd

Without the fpd daemon active, it creates a new FPD, stores it in the local db without sending any transactions to the chain, I will add a description to the CLI

2024-04-18 10:40 UTC, RafilxTenfen commented on finality-provider/cmd/fpcli/daemon/export-fpd.go
> +		SlashedBtcHeight:     0,
I agree, but the structure being exported here is the same one we can import on the genesis btc staking module

So, setting these stateful fields helps a little the import phase, where we don't need another protobuf finality provider structure to parse this

2024-04-18 10:48 UTC, RafilxTenfen commented on finality-provider/cmd/fpcli/daemon/export-fpd.go
> +		cli.StringFlag{
done at https://github.com/babylonchain/finality-provider/pull/286/commits/e8ae68062ba0b4a76c8b8147cd4031ec4d1a310f

2024-04-18 11:19 UTC, SebastianElvis approved these changes
Lgtm! Would be great to get feedback from @gitferry as well :+1:

2024-04-18 18:33 UTC, RafilxTenfen commented on docs/finality-provider-export.md
> +- [fpd](https://github.com/babylonchain/finality-provider)
what do you think about linking it ? https://github.com/babylonchain/finality-provider/pull/286/commits/ef56bc4a456fa04a0b0252ebde483b2a8c10e5df

2024-04-18 18:33 UTC, RafilxTenfen commented on docs/finality-provider-export.md
> +Similar to any native PoS validator, a finality provider can receive voting power delegations from BTC stakers, and
done at https://github.com/babylonchain/finality-provider/pull/286/commits/9917b4e1cb4b4e70a06d887f89be0ef1d3983852

2024-04-18 18:39 UTC, RafilxTenfen commented on docs/finality-provider-export.md
> +## Requirements
done at https://github.com/babylonchain/finality-provider/pull/286/commits/6e5ef32bc2451fa38ca548e6645a4d4323a52148

2024-04-18 18:42 UTC, RafilxTenfen commented on finality-provider/cmd/fpcli/daemon/export-fpd.go
agree, is already inside `finality-provider`

2024-04-18 18:46 UTC, RafilxTenfen commented on finality-provider/cmd/fpcli/daemon/export-fpd.go
> +randomness pair, stores the finality provider and export it by printing the json
done at https://github.com/babylonchain/finality-provider/pull/286/commits/9931d4cf2c5cbb82dfbc13c38aa4bc494a5b579f

2024-04-18 18:46 UTC, RafilxTenfen commented on finality-provider/cmd/fpcli/daemon/export-fpd.go
> +	Usage:     "Create, stores, and exports one finality provider.",
done at https://github.com/babylonchain/finality-provider/pull/286/commits/9931d4cf2c5cbb82dfbc13c38aa4bc494a5b579f

2024-04-18 18:46 UTC, RafilxTenfen commented on finality-provider/cmd/fpcli/daemon/export-fpd.go
> +	ShortName: "exfpd",
done at https://github.com/babylonchain/finality-provider/pull/286/commits/9931d4cf2c5cbb82dfbc13c38aa4bc494a5b579f

2024-04-19 03:07 UTC, gitferry reviewed
After thinking more about this, I feel like the `export-finality-provider` cmd introduced here actually creates a finality provider and prints out the infomation. The creating part seems unnecessary. What if the user loses the info and wants to export it again? Maybe we can use the old `create-finality-provider` cmd to create the finality provider and export it by specifying the `btc-pk`? e.g., `fpcli export-finality-provider --btc-pk xxxxxx path/to/json`, which will not succeed if specified finality provider does not exist.

The current issue with `create-finality-provider` is that it requires `fpd` to run and `fpd start` will start all the existing finality providers, which are not needed if we only need to export a created one. Maybe we just need to introduce something like a `pure` mode to just start `fpd` without running existing finality providers. Nevertheless, I think relying the running of `fpd` is necessary because it is the `fpd` that controls the db and we should not let `fpcli` to connect to db directly. This way, validators can just follow the previous guidance to create finality providers and export it with an additional cmd. Wdyt? cc @vitsalis @SebastianElvis 

So, I propose the following changes based on this PR (or we can make it in a new PR if you feel cleaner):
1. remove the creation part of the current `export-finality-provider` and allow export by specifying `btc-pk` and sending a rpc request to `fpd` to get the data, similar to `fpcli finality-provider-info`.
2. introduce a `pure` mode to `fpd start` to allow the daemon to start without initiating any existing finality providers
3. the export part of the `docs/finality-provider-export.md` can be moved to `docs/finality-provider.md` with some changes about the introducing of `pure` mode to `fpd start` when creating finality providers

Left some comments on the doc which probably can be ignored with the proposed changes are agreed:

2024-04-19 11:26 UTC, RafilxTenfen commented
> The current issue with `create-finality-provider` is that it requires `fpd` to run 

and also connects to the bbn chain to register the fp by the transaction, this command `export-finality-provider` could even be removed after the phase-1 sunset, the idea was to make it simple for the finality provider to generate the needed information for registration. 

In a better scenario, we would not even need to run `eotsd`, this cli would connect directly to the eotsd db, but doing that would mess up a lot the code

2024-04-19 11:35 UTC, RafilxTenfen commented on docs/finality-provider-export.md
> +### Setup EOTS
done at https://github.com/babylonchain/finality-provider/pull/286/commits/503d663df53b4c991a0670dc21a7d0f43704265e

2024-04-19 11:35 UTC, RafilxTenfen commented on docs/finality-provider-export.md
> +home location, unless `--home` flag is specified.
done at https://github.com/babylonchain/finality-provider/pull/286/commits/503d663df53b4c991a0670dc21a7d0f43704265e

2024-04-19 11:35 UTC, RafilxTenfen commented on docs/finality-provider-export.md
> +### Setup fpd
done at https://github.com/babylonchain/finality-provider/pull/286/commits/503d663df53b4c991a0670dc21a7d0f43704265e

2024-04-19 11:35 UTC, RafilxTenfen commented on docs/finality-provider-export.md
> +- `fpcli`
done at https://github.com/babylonchain/finality-provider/pull/286/commits/503d663df53b4c991a0670dc21a7d0f43704265e

2024-04-19 11:35 UTC, RafilxTenfen commented on docs/finality-provider-export.md
> +in the default home location, unless `--home` flag is specified.
done at https://github.com/babylonchain/finality-provider/pull/286/commits/503d663df53b4c991a0670dc21a7d0f43704265e

2024-04-19 11:35 UTC, RafilxTenfen commented on docs/finality-provider-export.md
> +> Store safely the mnemonic generated
done at https://github.com/babylonchain/finality-provider/pull/286/commits/503d663df53b4c991a0670dc21a7d0f43704265e

2024-04-19 11:35 UTC, RafilxTenfen commented on docs/finality-provider-export.md
> +## Creation & Export of Finality provider
done at https://github.com/babylonchain/finality-provider/pull/286/commits/503d663df53b4c991a0670dc21a7d0f43704265e

2024-04-19 11:48 UTC, gitferry commented
> and also connects to the bbn chain to register the fp by the transaction, this command export-finality-provider could even be removed after the phase-1 sunset, the idea was to make it simple for the finality provider to generate the needed information for registration.

`create-finality-provider` does not do the registration. We have `register-finality-provider` to do that.

2024-04-19 12:16 UTC, RafilxTenfen commented
> `create-finality-provider` does not do the registration. We have `register-finality-provider` to do that.

true

So in this case, @gitferry  the idea is:
1. Run `eotsd init`
2. Run `eotsd start`
3. Run `fpd init`
4. Run `fpd start --no--bbn` (or something like that) to not connect to the client controller in the app
5. Run `fpcli create-finality-provider` generate the fp and output to the user the `btc_pk_hex` (key for getting the fp from the store)
6. Can turn down `eotsd`
7. Run `fpcli export-finality-provider --btc-pk-hex [btc_pk_hex]` to export the previously created finality provider by connecting to fpd process (not connecting directly to the kv database)
8. Can turn down `fpd`

I liked, this way we can maintain the export even after the phase-1

2024-04-19 12:27 UTC, gitferry commented
All steps are valid 👍. Just a note that we don't ask users to turn down daemons in the instructions but we can add a note in step 7 that this command does not rely on `eotsd` running

2024-04-19 17:34 UTC, vitsalis commented
We should also include instructions for safe-keeping and not losing the finality provider key.

2024-04-22 14:30 UTC, RafilxTenfen commented
@gitferry I had not merged the `docs/finality-provider-export.md` into `docs/finality-provider.md` file, because it explains different perspectives, the export one setups eotsd and fpd just for generating information that finality providers will use to submit their information 
In a latter phase, we can have another set of instructions just for they to turn fpd and eotsd up when the chain starts

2024-04-22 14:35 UTC, gitferry reviewed
Thanks for the change. Great work! Some small comments:

2024-04-22 14:35 UTC, gitferry commented on finality-provider/cmd/fpcli/daemon/export.go
> +	Usage:     "Creates, stores, and exports one finality provider.",
```suggestion
	Usage:     "It exports the finality provider by the given public key.",
```

2024-04-22 14:35 UTC, gitferry commented on finality-provider/cmd/fpcli/daemon/export.go
> +structure on the stdout`,
```suggestion
	Description: `Fetches the finality provider from the database and exports it by printing the json
structure on the stdout`,
```

2024-04-22 14:35 UTC, gitferry commented on finality-provider/cmd/fpcli/daemon/export.go
> +			if true, it is necessary to define keyring flags`,
```suggestion
			if true, it is necessary to define the key name flag`,
```

2024-04-22 14:35 UTC, gitferry commented on finality-provider/cmd/fpcli/daemon/export.go
> +
Do we need to check whether the key name is specified if `signed` is true?

2024-04-22 14:35 UTC, gitferry commented on finality-provider/cmd/fpcli/daemon/export.go
> +	FpSigHex string `json:"fp_sig_hex"`
what do we need this sig for?

2024-04-22 14:35 UTC, gitferry commented on finality-provider/cmd/fpd/daemon/start.go
> +	noBabylonChainFlag = "no-bbn"
```suggestion
	noChainBackendFlag = "no-chain-backend"
```

2024-04-22 14:35 UTC, gitferry commented on finality-provider/cmd/fpd/daemon/start.go
> +			Usage: "If specified, does not connect to client controller",
```suggestion
			Usage: "If specified, does not connect to the chain backend",
```

2024-04-22 14:35 UTC, gitferry commented on finality-provider/cmd/fpd/daemon/start.go
>  	fpApp, err := service.NewFinalityProviderAppFromConfig(cfg, dbBackend, logger)
why does it relate to Eots? Maybe we can just insert the chain controller as an additional input to the function

2024-04-22 14:36 UTC, gitferry approved these changes

2024-04-22 15:37 UTC, vitsalis commented on docs/finality-provider-export.md
> +After the proper configuration, start the etos daemon with the command `eotsd start`.
```suggestion
After the proper configuration, start the eots daemon with the command `eotsd start`.
```

2024-04-22 15:37 UTC, vitsalis commented on docs/finality-provider-export.md
> +and providing finality signatures if it has voting power. To initialize the `fpd`
```suggestion
and providing finality signatures if it is in the active finality provider set.
To initialize the `fpd`
```

2024-04-22 15:37 UTC, vitsalis commented on docs/finality-provider-export.md
> +The home golder should point to the work directory previously created with `fpd init`
The above need to be wrapped to 80 char lines

2024-04-22 15:37 UTC, vitsalis commented on docs/finality-provider-export.md
> +After the setup of the configuration and key to be used, start the `fpd` daemon with the command `fpd start` with no babylon chain `--no-bbn`.
Should we say why no Babylon chain is needed?

2024-04-22 15:37 UTC, vitsalis commented on docs/finality-provider-export.md
> +daemon, it is used the `fpcli`. To create the finality provider, run
```suggestion
daemon, you can use the `fpcli` utility. To create the finality provider, run
```

2024-04-22 15:37 UTC, vitsalis commented on docs/finality-provider-export.md
> +> Obs.: This command does not send a transaction to babylon chain `babylond tx btcstaking create-finality-provider`.
I don't get this line, why do we specify the babylon cli here?

2024-04-22 15:37 UTC, vitsalis commented on docs/finality-provider-export.md
> +The expected result is a finality with 5% comission exported:
Why do we specify the commission here? Someone might think that we always output 5% commission. I would remove it.

2024-04-22 17:37 UTC, RafilxTenfen commented on finality-provider/cmd/fpcli/daemon/export.go
> +	Usage:     "Creates, stores, and exports one finality provider.",
good catch, my bad did not revised the descriptions :/

2024-04-22 17:47 UTC, RafilxTenfen commented on finality-provider/cmd/fpcli/daemon/export.go
> +
by default if `--key-name` flag is not set, loads from config
If there is nothing on config, it errors out

2024-04-22 17:48 UTC, RafilxTenfen commented on finality-provider/cmd/fpcli/daemon/export.go
> +	FpSigHex string `json:"fp_sig_hex"`
The idea is to make explicit that nobody modified the finality provider information once generated.
It is proof that the finality provider generated that information with those descriptions and more importantly, the pub keys and commission

2024-04-22 17:57 UTC, RafilxTenfen commented on finality-provider/cmd/fpcli/daemon/export.go
> +// signed finality probider by the bbn pub key as hex
done at https://github.com/babylonchain/finality-provider/pull/286/commits/b100888615e074809063e7789252032444bd7876

2024-04-22 17:57 UTC, RafilxTenfen commented on finality-provider/cmd/fpcli/daemon/export.go
> +	Usage:     "Creates, stores, and exports one finality provider.",
done at https://github.com/babylonchain/finality-provider/pull/286/commits/2adcd440abeaea18488d2edb6b93138dddbe776c

2024-04-22 17:58 UTC, RafilxTenfen commented on finality-provider/cmd/fpcli/daemon/export.go
> +structure on the stdout`,
https://github.com/babylonchain/finality-provider/pull/286/commits/2adcd440abeaea18488d2edb6b93138dddbe776c

2024-04-22 17:59 UTC, RafilxTenfen commented on finality-provider/cmd/fpcli/daemon/export.go
> +
also, when submitting this information for us, we have a way for the CI to verify if the signature matches
https://github.com/babylonchain/finality-provider/pull/290

Let me know what you think about this

2024-04-22 18:00 UTC, RafilxTenfen commented on finality-provider/cmd/fpcli/daemon/export.go
> +	FpSigHex string `json:"fp_sig_hex"`
When submitting this finality provider information for us, we have a way for the CI to verify if the signature matches
https://github.com/babylonchain/finality-provider/pull/290

Let me know what you think about this

2024-04-22 18:01 UTC, RafilxTenfen commented on finality-provider/cmd/fpd/daemon/start.go
> +	noBabylonChainFlag = "no-bbn"
done at https://github.com/babylonchain/finality-provider/pull/286/commits/0b19b133d19ccdd03743ed6ef827065d138981dd

2024-04-22 18:01 UTC, RafilxTenfen commented on finality-provider/cmd/fpd/daemon/start.go
> +			Usage: "If specified, does not connect to client controller",
https://github.com/babylonchain/finality-provider/pull/286/commits/0b19b133d19ccdd03743ed6ef827065d138981dd

2024-04-22 18:01 UTC, RafilxTenfen commented on finality-provider/cmd/fpd/daemon/start.go
>  	fpApp, err := service.NewFinalityProviderAppFromConfig(cfg, dbBackend, logger)
https://github.com/babylonchain/finality-provider/pull/286/commits/73ff4dd7ab0566921078b2742d4fb4ead3c3d58f

2024-04-22 18:07 UTC, RafilxTenfen commented on docs/finality-provider-export.md
> +After the proper configuration, start the etos daemon with the command `eotsd start`.
https://github.com/babylonchain/finality-provider/pull/286/commits/c24afebdef4c435f69b345989989efda404ff596

2024-04-22 18:08 UTC, RafilxTenfen commented on docs/finality-provider-export.md
> +and providing finality signatures if it has voting power. To initialize the `fpd`
https://github.com/babylonchain/finality-provider/pull/286/commits/5d51cd265c9fd1ba3096f6365f223e61af64881b

2024-04-22 18:15 UTC, RafilxTenfen commented on docs/finality-provider-export.md
> +The home golder should point to the work directory previously created with `fpd init`
https://github.com/babylonchain/finality-provider/pull/286/commits/deb3c487d0427149bfe20f99f0f04fc7dff1f1b8
https://github.com/babylonchain/finality-provider/pull/286/commits/5d51cd265c9fd1ba3096f6365f223e61af64881b

2024-04-22 18:29 UTC, RafilxTenfen commented on docs/finality-provider-export.md
> +After the setup of the configuration and key to be used, start the `fpd` daemon with the command `fpd start` with no babylon chain `--no-bbn`.
https://github.com/babylonchain/finality-provider/pull/286/commits/1892c9ae733df3e0c17cbc8be3c84b8cdc5f0a67

2024-04-22 18:31 UTC, RafilxTenfen commented on docs/finality-provider-export.md
> +daemon, it is used the `fpcli`. To create the finality provider, run
https://github.com/babylonchain/finality-provider/pull/286/commits/0a0e83ee02d41ccf9607118a7732af5274e6b257

2024-04-22 18:34 UTC, RafilxTenfen commented on docs/finality-provider-export.md
> +The expected result is a finality with 5% comission exported:
removed at https://github.com/babylonchain/finality-provider/pull/286/commits/0c72c3bd18cec397af881f69eb228fcb5d5a1831

2024-04-23 01:34 UTC, RafilxTenfen commented
![image](https://github.com/babylonchain/finality-provider/assets/17556614/5a510281-7fa2-4d9c-a3e6-13e8263b4a71)

2024-04-23 12:14 UTC, RafilxTenfen commented on docs/finality-provider-export.md
> +⚠ Keep the compressed directory stored securely.
New section that explains what happens if the keys are lost, should I mention that no BTC would be lost even if the finality provider lost the keys? 
@vitsalis

2024-04-23 12:41 UTC, vitsalis commented on docs/finality-provider-export.md
> +It creates the default home location, unless `--home` flag is specified.
What's the default home location?

2024-04-23 12:41 UTC, vitsalis commented on docs/finality-provider-export.md
> +> is exported (run all commands of this file).
```suggestion
> The eots process can be turned down after this guide is completed
> if the goal is to just export the finality provider and not connect it to a PoS chain.
```

2024-04-23 12:41 UTC, vitsalis commented on docs/finality-provider-export.md
> +The finality provider daemon (fpd) is responsible for polling consumer chain blocks
```suggestion
The finality provider daemon (`fpd`) is responsible for polling consumer chain blocks
```

2024-04-23 12:41 UTC, vitsalis commented on docs/finality-provider-export.md
> +[backend keyring](https://docs.cosmos.network/v0.45/run-node/keyring.html#available-backends-for-the-keyring)
```suggestion
[keyring backend](https://docs.cosmos.network/v0.45/run-node/keyring.html#available-backends-for-the-keyring)
```

2024-04-23 12:41 UTC, vitsalis commented on docs/finality-provider-export.md
> +, one of `[os, file, pass, kwallet]`.
```suggestion
, i.e. one of `[os, file, pass, kwallet]`.
```

2024-04-23 12:41 UTC, vitsalis commented on docs/finality-provider-export.md
> +No chain backend is needed to create and export the finality provider information.
```suggestion
with the command `fpd start`. If you want to just export the finality provider info without
connecting to a PoS chain, then you can use the flag `--no-chain-backend`.
```

Don't think `--no-chain-backend` is a pre-requisite for exporting, right?

2024-04-23 12:41 UTC, vitsalis commented on docs/finality-provider-export.md
> +After the setup and start of `eots` and `fdp`, to interact with the `fpd`
```suggestion
After the setup and start of `eots` and `fpd`, to interact with the `fpd`
```

2024-04-23 12:41 UTC, vitsalis commented on docs/finality-provider-export.md
> +> Obs.: This command does not send a transaction to babylon chain.
```suggestion
> Obs.: This command only registers the finality provider in the local `fpd` database and not to the Babylon chain, meaning that it can be ran without a connection to it.
```

2024-04-23 12:41 UTC, vitsalis commented on docs/finality-provider-export.md
> +Finally, after the creation of the finality provider, to export the finality
```suggestion
Finally, after the creation of the finality provider in the local db, to export the finality
```

2024-04-23 12:41 UTC, vitsalis commented on docs/finality-provider-export.md
> +`fpd` daemon to load the finality provider previously created using the flag `--btc-pk`.
```suggestion
`fpd` daemon to load the finality provider previously created using the flag `--btc-pk`
to specify the BTC public key that acts as the unique identifier for it.
```

2024-04-23 12:41 UTC, vitsalis commented on docs/finality-provider-export.md
> +- `--key-name` mandatory as it identifies the name for the key to use on fpd creation.
Why is `key-name` and not `btc-pk` the mandatory flag? I would expect that we can find the finality provider just with the `--btc-pk`.

2024-04-23 12:41 UTC, vitsalis commented on docs/finality-provider-export.md
> +This command also has several flag options.:
Shouldn't we specify `--keyring-backend` as well here?

2024-04-23 12:41 UTC, vitsalis commented on docs/finality-provider-export.md
> +information that will be used latter for running the finality provider.
```suggestion
> In the case that there is no Babylon chain running, but you intend to connect to it
once it is up, you should keep the database folders of `eotsd` and `fpd` securely stored
as they are necessary for retrieving your finality provider and registering it with the chain.
```

2024-04-23 17:41 UTC, RafilxTenfen commented on docs/finality-provider-export.md
> +information that will be used latter for running the finality provider.
file removed

2024-04-23 17:43 UTC, RafilxTenfen commented on docs/finality-provider-export.md
> +It creates the default home location, unless `--home` flag is specified.
$HOME/.eotsd

2024-04-23 17:50 UTC, RafilxTenfen commented
As discussed, removed flag for start `fpd` without bbn chain 
Removed specific .md file for export CLI and add an export example to `finality-provider.md`

2024-04-24 09:38 UTC, vitsalis approved these changes
Nice work! Minor comments

2024-04-24 09:38 UTC, vitsalis commented on finality-provider/cmd/fpcli/daemon/export.go
> +			Usage: `Defines if needs to sign the exported finality provider,
```suggestion
			Usage: `Specify if the exported finality provider information should be signed,
```

2024-04-24 09:38 UTC, vitsalis commented on finality-provider/cmd/fpcli/daemon/export.go
> +	fpInfoResp, err := client.QueryFinalityProviderInfo(context.Background(), fpPk)
```suggestion
	fpInfoResp, err := client.QueryFinalityProviderInfo(ctx, fpPk)
```

2024-04-24 09:38 UTC, vitsalis commented on finality-provider/cmd/fpcli/daemon/export.go
> +		context.Background(),
```suggestion
		ctx,
```

2024-04-24 09:38 UTC, vitsalis commented on finality-provider/service/app.go
> +	keyName, passPhrase, hdPath string,
Is a passphrase and hdpath required? What happens if they are not set?

2024-04-24 11:02 UTC, RafilxTenfen commented on docs/finality-provider.md
> +- `--key-name` mandatory as it identifies the name for the key to use on fpd creation.
my bad, key-name flag is only necessary if the export should be signed and there is no key-name set on config
I will updated the description

2024-04-24 11:06 UTC, RafilxTenfen commented on docs/finality-provider.md
> +- `--passphrase` the password used to encrypt the key.
Since the `fpcli` does not load the keys, the App on `fpd` uses the keyring backend from config

2024-04-24 11:11 UTC, RafilxTenfen commented on finality-provider/cmd/fpcli/daemon/export.go
> +	fpInfoResp, err := client.QueryFinalityProviderInfo(context.Background(), fpPk)
the ctx in this case is `ctx *cli.Context` not able to parse it to `ctx context.Context`

2024-04-24 11:11 UTC, RafilxTenfen commented on finality-provider/cmd/fpcli/daemon/export.go
> +		context.Background(),
the ctx in this case is ctx *cli.Context not able to parse it to ctx context.Context

2024-04-24 11:12 UTC, RafilxTenfen commented on finality-provider/service/app.go
> +	keyName, passPhrase, hdPath string,
it accepts it as empty strings, so they are not required

2024-04-24 11:47 UTC, merged